apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
        version: new
    spec:
      containers:
      - name: netflix-app
        image: public.ecr.aws/s3e1v8a7/henops/netflix
        ports:
        - containerPort: 80
